name: Report Bugs
description: Create a report to help us improve
body: 
  - type: markdown
    attributes:
      value: |
        请提供以下信息
  - type: input
    attributes:
      label: Node.js Version
      description: Output of `node -v`
  - type: input
    attributes:
      label: Package Version
      description: Installed by npm or yarn
      placeholder: latest?
  - type: radio
    attributes:
      label: Login Protocol(Platform)
      description: Android
  - type: textarea
    attributes:
      label: Bug Description
  - type: textarea
    attributes:
      label: Detail Logs
