name: Bug汇报
description: 遇到了bug? 你可以在这里开始汇报（仅限软件本体问题）
body: 
  - type: markdown
    attributes:
      value: |
        在您发布此Issue前, 请您花一点时间查看下面几条指引🔽

        1: ❗ | 确定没有相同问题的ISSUE已被提出. (教程: https://github.com/Mrs4s/go-cqhttp/issues/633)
        2: 🌎| 请准确填写环境信息.
        3: ❔ | 打开DEBUG模式复现，并提供出现问题前后至少 10 秒的完整日志内容。请自行删除日志内存在的个人信息及敏感内容。
        4: ⚠ | 如果涉及内存泄漏/CPU占用异常请打开DEBUG模式并下载pprof性能分析.

        注: 如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》
        (链接: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

        请确保您已经仔细阅读此教程，并勾选下方的确认框。
        --------
        - [x] 我已经仔细阅读上述教程和"提问前需知 [图+文]": https://github.com/Mrs4s/go-cqhttp/issues/633
        - [x] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，则我的 Issue 可能会被无条件自动关闭和锁定。
        - [x] 我已知晓并同意，我仅需要把选项前的 [ ] 替换为 [x]。如果我删除、修改这些复选框的其他部分，或是在 x 之前或之后留了空格，则我的 Issue 可能会被无条件自动关闭和锁定。
        - [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题或是新功能需求，则我的 Issue 可能会被无条件自动关闭和锁定。（这些问题应当在 Discussion 板块提出。）
        --------
  - type: input
    id: 1
    attributes:
      label: go-cqhttp版本
  - type: input
    id: 2
    attributes:
      label: 运行环境
  - type: dropdown
    id: 3
    attributes:
      label: 连接方式
      options:
        - http
        - 正向ws
        - 反向ws
        - 长轮询
  - type: dropdown
    id: 4
    attributes:
      label: 使用协议
      options:
        - 安卓手机
        - 安卓手表
        - iMac
        - iPad
        - 企点
  - type: textarea
    id: 5
    attributes:
      label: bug内容
  - type: textarea
    id: 6
    attributes:
      label: 复现方法
  - type: textarea
    id: 7
    attributes:
      label: 详细日志
